//
//  modelTable.m
//  infoMobile
//
//  Created by User on 4/17/14.
//  Copyright (c) 2014 Jerry. All rights reserved.
//

#import "searchCar.h"
#import "modelTable.h"

static NSString* modelLabel;

@implementation modelTable
@synthesize modelName;

//Keep portrait
- (NSUInteger)supportedInterfaceOrientations{
    return UIInterfaceOrientationMaskPortrait;
}

-(void)viewWillAppear:(BOOL)animated{
        [self.navigationController setToolbarHidden:YES];
}

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    //Initial Dictionary
    models = @{ @"A" : @[@"AAA",
                         @"AAA Chicago Motor",
                         @"AAR Eagle",
                         @"Abbott-Detroit",
                         @"AC",
                         @"AC Cobra",
                         @"Acura",
                         @"Adler",
                         @"Adventure",
                         @"Aermacchi",
                         @"AHRA",
                         @"AHRA Class Champ",
                         @"AHRA Eliminator",
                         @"AHRA Grand",
                         @"Ahrens-Fox",
                         @"Airfloat",
                         @"Airstream",
                         @"Aj Watson",
                         @"AJS",
                         @"Alamo Dragway",
                         @"Alcyon",
                         @"Alfa Romeo",
                         @"Alfa-Romeo",
                         @"All Star",
                         @"All-Cars Charly",
                         @"Allard",
                         @"Allegro",
                         @"Allis",
                         @"Allis Chalmers",
                         @"Allis-Chalmers",
                         @"Allstate Sears",
                         @"Alstate",
                         @"Alvis-6",
                         @"Am General",
                         @"Amalie",
                         @"AMC",
                         @"Amen",
                         @"Amer",
                         @"American",
                         @"American Austin",
                         @"American Bosch",
                         @"American General",
                         @"American Iron",
                         @"American Ironhorse",
                         @"American Motors",
                         @"AMF Harley-Davidson",
                         @"Amg",
                         @"Amphicar",
                         @"Ancarrow",
                         @"Anglia",
                         @"Antar Oil",
                         @"Apache",
                         @"Apex",
                         @"Aprilia",
                         @"Aquasco Speedway",
                         @"Arabella",
                         @"Arctic Cat",
                         @"Argosy",
                         @"Ariel",
                         @"Aristocraft",
                         @"Arlen Ness",
                         @"Arnolt",
                         @"Arrow",
                         @"Asbl",
                         @"Ask For",
                         @"ASM",
                         @"ASPT",
                         @"Assembled",
                         @"Assembled Parts",
                         @"Assembly",
                         @"Aston Martin",
                         @"Astra",
                         @"Asve",
                         @"Atc",
                         @"Atc Crawler",
                         @"Atc Raven",
                         @"Atlantic Gasoline",
                         @"Atlantic Neon Sign",
                         @"Auburn",
                         @"Audi",
                         @"Austin",
                         @"Austin Healey",
                         @"Austin J40",
                         @"Austin-Healey",
                         @"Austin-Morris",
                         @"Auto Club Of Cali",
                         @"Auto Racing",
                         @"Autokraft",
                         @"Avanti",
                         @"Avery",
                         @"Avid Magnum",],
                @"B" : @[@"Back Roads",
                         @"Backdraft",
                         @"Bagley",
                         @"Baja",
                         @"Baker",
                         @"Bally Super Bowler",
                         @"Bantam",
                         @"Barnsdall Products",
                         @"Batman & Dick Tracy",
                         @"Batmobile",
                         @"Bemis",
                         @"Benelli",
                         @"Bentley",
                         @"BF Avery",
                         @"Bianchi",
                         @"Bianchina",
                         @"Big Bear",
                         @"Big Bear Chopper",
                         @"Big Dog",
                         @"Big Inch Bike",
                         @"Big Wheel",
                         @"Bimota",
                         @"Black Metal",
                         @"Black Widow",
                         @"BMW",
                         @"Boat Tail",
                         @"Boat Trailer",
                         @"Boldie Russo",
                         @"Bolens",
                         @"Borum",
                         @"Boss",
                         @"Boss Hoss",
                         @"Bourget",
                         @"Bown",
                         @"Bowser",
                         @"Brainerd Robbins",
                         @"Brass",
                         @"Brass Cash Register",
                         @"Brazier",
                         @"Bricklin",
                         @"Bridgestone",
                         @"British",
                         @"British Leyland",
                         @"Brother",
                         @"Brough",
                         @"Bruce Larson",
                         @"BSA",
                         @"Bud Light",
                         @"Budweiser",
                         @"Buehler Turbocraft",
                         @"Buel",
                         @"Buell",
                         @"Bugatti",
                         @"Buick",
                         @"Buick Special",
                         @"Bull Tractor Co.",
                         @"Bultaco",],
                @"C" : @[@"Cabriolet",
                         @"Cadillac",
                         @"Cagiva",
                         @"California Motorcyle",
                         @"Callaway",
                         @"Calthorpe Ivory",
                         @"Camaro",
                         @"Camaro Hot Rod",
                         @"Camel Joe",
                         @"Canaday Brothers",
                         @"Canadian Electric",
                         @"Cannon Ball",
                         @"Car Craft",
                         @"Carabela",
                         @"Carefree",
                         @"Cargo Mate",
                         @"Cargomate",
                         @"Carryontrail",
                         @"Cars 2",
                         @"Case",
                         @"Caterpillar",
                         @"CAV",
                         @"CCC",
                         @"CCM",
                         @"Cee Bee",
                         @"Century",
                         @"Champion",
                         @"Chan",
                         @"Chandler",
                         @"Chang Jiang",
                         @"Chaparral",
                         @"Charger",
                         @"Checker",
                         @"Cheetah",
                         @"Chevrolet",
                         @"Chevrolet Corvette",
                         @"Chevrolet Showroom",
                         @"Chevy",
                         @"Chevy Jim Beam",
                         @"Chevy Vega",
                         @"Chief Tan",
                         @"Chinook",
                         @"Chopper",
                         @"Chopper Nation",
                         @"Chris Craft",
                         @"Chris-Craft",
                         @"Chris-Craft/Dewhurst",
                         @"Chrisman",
                         @"Chrysler",
                         @"Cigarette",
                         @"Citation",
                         @"Cities Service",
                         @"Citroen",
                         @"Citron",
                         @"Clac",
                         @"Clark",
                         @"Classic",
                         @"Classic Roadster",
                         @"Cletrac",
                         @"Cleveland",
                         @"Club Car",
                         @"Club Reman Ds",
                         @"Co-Op",
                         @"Cobra",
                         @"Coca Cola",
                         @"Coca-Cola",
                         @"Coca-Cola Billboard",
                         @"Cockshutt",
                         @"Coin Operated",
                         @"Colonel Tom Parker",
                         @"Columbia",
                         @"Comet",
                         @"Competitive",
                         @"Competitive Built",
                         @"Condor",
                         @"Condor/Ducati",
                         @"Confederate",
                         @"Continental",
                         @"Continential",
                         @"Coop",
                         @"Cooper",
                         @"COPO L72 427",
                         @"Cord",
                         @"Correct Craft",
                         @"Corvette",
                         @"Corvette Bank",
                         @"Corvette FI",
                         @"Corvette ZR1",
                         @"Cotton",
                         @"Country Coach",
                         @"Covenent",
                         @"Crawford",
                         @"Crocker",
                         @"Crosley",
                         @"Cruzzer",
                         @"Cub",
                         @"Cub Cadet",
                         @"Culbert",
                         @"Cunningham",
                         @"Cushman",
                         @"Custom",
                         @"Custom Built",
                         @"Custom Chopper",
                         @"Custom/spec",
                         @"Cyclops",
                         @"CZ",],
                @"D" : @[@"Daimler",
                         @"Dallara",
                         @"Dan Kidney",
                         @"Datsun",
                         @"Dave Connolly",
                         @"de Havilland",
                         @"De Tomaso",
                         @"Death Race 2000",
                         @"Death Row",
                         @"Dee Wite",
                         @"Dekalb",
                         @"Delage",
                         @"Delco Batteries",
                         @"Delorean",
                         @"Delorian",
                         @"Delta",
                         @"Deluxe Kidillac",
                         @"Demon",
                         @"Derbi",
                         @"Desoto",
                         @"DeTomaso",
                         @"Deutz",
                         @"Devin",
                         @"Diablo",
                         @"Diamond",
                         @"Diamond T",
                         @"Dingle",
                         @"Dirty Bird",
                         @"Discovery",
                         @"Ditchburn",
                         @"Divco",
                         @"Division 1",
                         @"DKW",
                         @"Dneper",
                         @"Dodge",
                         @"Dodge Brothers",
                         @"Dodge Plymouth",
                         @"Donzi",
                         @"Doolittle",
                         @"Dort",
                         @"Doud",
                         @"Douglas",
                         @"Down And Out In",
                         @"Downs",
                         @"Dr Pepper",
                         @"Drag Racing",
                         @"Dragster",
                         @"Dragtimes",
                         @"Dry Lakes",
                         @"Dual",
                         @"Dual Ghia",
                         @"Ducati",
                         @"Duesenberg",
                         @"Duetz",
                         @"Dunkley",
                         @"Dunlop Neon Sign",
                         @"Dunphy",
                         @"Dunstall-Norton",
                         @"Duromold",
                         @"Dutch Star",
                         @"Dynaquest",],
                @"E" : @[@"Eagle",
                         @"Eagle-Picher",
                         @"Ed Roth",
                         @"Eddie Trotta",
                         @"Edmunds-Kenyon",
                         @"Edsel",
                         @"Egli-Vincent Godet",
                         @"Electric Car",
                         @"Eliminator",
                         @"Elite",
                         @"Elvis Presley",
                         @"Elvis The Soldier",
                         @"Empa Award",
                         @"Empire Nationals",
                         @"Enco",
                         @"Epic Coach",
                         @"Era",
                         @"Essex",
                         @"Esso",
                         @"Everett",
                         @"Everett Morrison",
                         @"Evinrude",
                         @"Evj",
                         @"Ex-go",
                         @"Excaliber",
                         @"Excalibur",
                         @"Excel",
                         @"Excelsior",
                         @"Exide",
                         @"Exile",
                         @"Exotic",
                         @"Eysink",
                         @"Ez-go",],
                @"F" : @[@"Facel Vega",
                         @"Factory Five",
                         @"Farm All",
                         @"Farmall",
                         @"Fast And Furious",
                         @"Featherlite",
                         @"Ferguson",
                         @"Ferrari",
                         @"Ferris Wheel",
                         @"Fiat",
                         @"Fiat-cisitalia",
                         @"Field Marshall",
                         @"Fiero",
                         @"Fire",
                         @"Firestone",
                         @"Firestone Neon Sign",
                         @"Fisker",
                         @"Fleetwood",
                         @"Flxible",
                         @"Flying Merkel",
                         @"FN",
                         @"Ford",
                         @"Ford A-1 Neon Sign",
                         @"Ford Dealership",
                         @"Ford Ferguson",
                         @"Ford Motor",
                         @"Ford Mustang",
                         @"Ford Service",
                         @"Fordson",
                         @"Forest River",
                         @"Formula",
                         @"Forsa",
                         @"Fountain",
                         @"Four Wheel Drive",
                         @"Foyt",
                         @"Fram Filters",
                         @"Framed Flyer",
                         @"Framed National",
                         @"Framed NHRA",
                         @"Framed Portrait",
                         @"Francis",
                         @"Francis-Barnett",
                         @"Francy Craft",
                         @"Franklin",
                         @"Frazer",
                         @"Frazer-Nash",
                         @"Freedom",
                         @"Freightliner",
                         @"Frht",
                         @"Fulton Seamless",
                         @"FWD",],
                @"G" : @[@"G-force",
                         @"Gar Wood",
                         @"Gar Wood/Michaud",
                         @"Gates Tire",
                         @"Gates Tires",
                         @"GCS",
                         @"GEM",
                         @"Gentry",
                         @"Geo",
                         @"Gforce",
                         @"Gilbarco",
                         @"Gilera",
                         @"Gillette Tires",
                         @"Gilmore",
                         @"Glassic",
                         @"Glasspar",
                         @"Glastron",
                         @"Glen L",
                         @"Glen-L",
                         @"Glenn Pray",
                         @"Globe",
                         @"GM",
                         @"GMC",
                         @"GMC Neon Sign",
                         @"Gnome & Rhone",
                         @"Go-4",
                         @"Goggomobil",
                         @"Goggomobile",
                         @"Golf Cart",
                         @"Good Gulf",
                         @"Goodhue & Hawkins",
                         @"Goodrich Neon Sign",
                         @"Goodyear",
                         @"Goodyear Neon Sign",
                         @"Goodyear Tire",
                         @"Goodyear Tires",
                         @"Goodyear Truck",
                         @"Goverse & Rotteveel",
                         @"Graham",
                         @"Grant King",
                         @"Greavette",
                         @"Griffith",
                         @"Grindlay-Peerless",
                         @"Grosser Preis",
                         @"Grump's",
                         @"Grumpy's Stuff",
                         @"Grumpy's Toy",
                         @"Gulf",
                         @"Gulf With Ears",
                         @"Gulfstream",
                         @"Gull",],
                @"H" : @[@"Hacker",
                         @"Hacker-Craft",
                         @"Hal",
                         @"Hall Of Fame",
                         @"Hand Start",
                         @"Hankinson",
                         @"Harley Davidson",
                         @"Harley J. Earl",
                         @"Harley-Davidson",
                         @"Harris",
                         @"Harris Matchless",
                         @"Hart Parr",
                         @"Haulin",
                         @"Haulmark",
                         @"Hawthorne",
                         @"Healey",
                         @"Hefty",
                         @"Heinkel",
                         @"Henderson",
                         @"Hendrick Motorsports",
                         @"Hennessey",
                         @"Henney",
                         @"Henry J",
                         @"Hercules",
                         @"Herter Duofoil",
                         @"Hi-Speed Neon Sign",
                         @"Hiawatha",
                         @"Hickman",
                         @"Higgins",
                         @"Hillegass",
                         @"Hiller Comet",
                         @"Hispano-Suiza",
                         @"Hobart",
                         @"Hodaka",
                         @"Holiday",
                         @"Holiday Rambler",
                         @"Home",
                         @"Home Made",
                         @"Homebuilt",
                         @"Homemade",
                         @"Honda",
                         @"Hondo",
                         @"Hood Tires Saluting",
                         @"Horex",
                         @"Horn Seed",
                         @"Horse Drawn",
                         @"Hot Cars",
                         @"Hot Wheels",
                         @"House",
                         @"Howard",
                         @"Hudson",
                         @"Huffaker Genie",
                         @"Hummer",
                         @"Hunter",
                         @"Hupmobile",
                         @"Hupp",
                         @"Husqvarna",
                         @"Hutchinson",
                         @"Hydra-Sports",
                         @"Hyundai",],
                @"I" : @[@"IH",
                         @"IH Cub Cadet",
                         @"IH Farmall",
                         @"Ihc",
                         @"Imme",
                         @"Imperial",
                         @"Imperial Industries",
                         @"Indian",
                         @"Indian Chief",
                         @"Indian Lakes",
                         @"Inductee",
                         @"Indy",
                         @"Infiniti",
                         @"Ingalls",
                         @"Innocenti",
                         @"International",
                         @"International Farmal",
                         @"International Harves",
                         @"Iron Horse",
                         @"Iron Works",
                         @"Isotta",
                         @"Isuzu",],
                @"J" : @[@"J-2000",
                         @"Jackie Stewart",
                         @"Jaguar",
                         @"James",
                         @"JAP",
                         @"Jawa",
                         @"JBL",
                         @"Jeep",
                         @"Jeepster",
                         @"Jefferson",
                         @"Jensen",
                         @"Jensen Healey",
                         @"Jim Davis",
                         @"Joe Shaheen",
                         @"John Deere",
                         @"Johnson",
                         @"Jungle Jim",],
                @"K" : @[@"Kaiser",
                         @"Kaiser Darrin",
                         @"Kaiser Frazer",
                         @"Kaiser Jeep",
                         @"Kaiser-Darrin",
                         @"Kandi",
                         @"Kannon",
                         @"Kaufman",
                         @"Kawasaki",
                         @"Kawaski",
                         @"Kenworth",
                         @"Kermath",
                         @"Kerry",
                         @"Kirkham",
                         @"Kissel",
                         @"Kit",
                         @"Kith",
                         @"Kitv Porsche",
                         @"Kodiak",
                         @"Kom-pak",
                         @"KR Proton",
                         @"Kraft Tech",
                         @"KTM",
                         @"Kubota",
                         @"Kurtis",
                         @"Kurtis Kraft",
                         @"Kurtis-Kraft",
                         @"Kurtis/Taffanelli",],
                @"L" : @[@"L&M Grand Prix",
                         @"La Salle",
                         @"Laforza",
                         @"Lagonda",
                         @"Lakeshore",
                         @"Lamborghini",
                         @"Lamborgihni",
                         @"Lambretta",
                         @"Lancia",
                         @"Land Rover",
                         @"Larson",
                         @"Lasalle",
                         @"Lauterbach",
                         @"Laverda",
                         @"Lawwill",
                         @"Le Mans",
                         @"Leader",
                         @"Legends",
                         @"Lexus",
                         @"Leyare",
                         @"Limited Edition",
                         @"Lincoln",
                         @"Little Guy",
                         @"Locomobile",
                         @"Lola",
                         @"Look",
                         @"Lotus",
                         @"Lucky Devil",
                         @"Lusse Auto Skooter",
                         @"Luyere",
                         @"Lyman",],
                @"M" : @[@"Mack",
                         @"Made-Rite",
                         @"Magnat-Debon",
                         @"Magnum",
                         @"Maico",
                         @"Malibu",
                         @"Manx",
                         @"Manx Norton",
                         @"March",
                         @"Margay",
                         @"Marin",
                         @"Mariner",
                         @"Martin Bros",
                         @"Marusho",
                         @"Marx",
                         @"Marx Ride-On",
                         @"Maserati",
                         @"Massey",
                         @"Massey Ferguson",
                         @"Massey Harris",
                         @"Massey-Ferguson",
                         @"Massey-harris",
                         @"Massy Harris",
                         @"Massy Wallis",
                         @"Matchless",
                         @"Matt Hotch",
                         @"Matthews Company",
                         @"Maxwell",
                         @"Maybach",
                         @"Mazda",
                         @"McBurnie",
                         @"Mcc",
                         @"Mccormick",
                         @"Mccormick Deering",
                         @"Mccormick Farmall",
                         @"Mccormick-Deering",
                         @"Mclaren",
                         @"Megaforce",
                         @"Memorabilia",
                         @"Memory Lane",
                         @"Mercedes",
                         @"Mercedes Benz",
                         @"Mercedes-Benz",
                         @"Mercer",
                         @"Mercury",
                         @"Merkel",
                         @"Merlyn",
                         @"Mert Lawwill",
                         @"Messerschmidt",
                         @"Messerschmitt",
                         @"Metal Dairy",
                         @"Meteor",
                         @"Metro",
                         @"Metropolitan",
                         @"Metz",
                         @"Meyers Manx",
                         @"MG",
                         @"MGA",
                         @"MGB",
                         @"Michael Shumacher",
                         @"Michael Turner",
                         @"Midget",
                         @"Midwest",
                         @"Midwest Custom",
                         @"Migi",
                         @"Mike Loves",
                         @"Military",
                         @"Military Jeep",
                         @"Miller",
                         @"Miller Tires",
                         @"Milocraft",
                         @"Mini",
                         @"Mini Cooper",
                         @"Minn. Moline",
                         @"Minneapolis",
                         @"Minneapolis Moline",
                         @"Minneapolis-Moline",
                         @"Mirage",
                         @"Mitchell",
                         @"Mitsubishi",
                         @"Mobil",
                         @"Mobil Gas",
                         @"Mobil Gas Pump",
                         @"Mobil Pegasus",
                         @"Mobilgas",
                         @"Mobiloil",
                         @"Mochet",
                         @"Modena",
                         @"Monaco",
                         @"Monaco Grand Prix",
                         @"Monark",
                         @"Monark Bicycle",
                         @"Mondial",
                         @"Monet",
                         @"Montesa",
                         @"Montgomery",
                         @"Moonrunners",
                         @"Moore",
                         @"Mopar",
                         @"Morgan",
                         @"Morris",
                         @"Morris Minor",
                         @"Mosler",
                         @"Moss",
                         @"Motiv",
                         @"Moto",
                         @"Moto Guzzi",
                         @"Moto Morini",
                         @"Motom",
                         @"Motorsports",
                         @"Motosacoche",
                         @"Moxie",
                         @"Mr.Mom",
                         @"Mti",
                         @"MTT Turbine",
                         @"Muntz",
                         @"Murray Pedal Car",
                         @"Murray Ranch Wagon",
                         @"Muskgo",
                         @"Mustang",
                         @"MV Agusta",
                         @"Myers Manx",
                         @"MZ",],
                @"N" : @[@"N.U.T.",
                         @"NASCAR",
                         @"Nash",
                         @"Nash Healey",
                         @"Nash-healey",
                         @"Ness",
                         @"New Era",
                         @"New Idea",
                         @"NHRA",
                         @"NHRA Eliminator",
                         @"NHRA Gator",
                         @"NHRA Land Of NED",
                         @"Nimbus",
                         @"Nissan",
                         @"Nitro",
                         @"Noble",
                         @"Norris Craft",
                         @"Norton",
                         @"Norton Atlas",
                         @"NOS DeKalb",
                         @"Nostalgia Dragfest",
                         @"NSU",],
                @"O" : @[@"Oakland",
                         @"OCC",
                         @"OEC",
                         @"Offenhauser",
                         @"Offeyette",
                         @"Offyette",
                         @"Olds",
                         @"Oldsmobile",
                         @"Oliver",
                         @"Opaline Neon Sign",
                         @"Opel",
                         @"Open Wheel",
                         @"Optima",
                         @"Orange County",
                         @"Original 12 Hours",],
                @"P" : @[@"Pabst",
                         @"Pace",
                         @"Pace American",
                         @"Packard",
                         @"Packard Clipper",
                         @"Pannonia",
                         @"Panoz",
                         @"Pantera",
                         @"Panther",
                         @"Parilla",
                         @"Pcam",
                         @"Peachstate",
                         @"Peerless",
                         @"Pegasus",
                         @"Pen Yan",
                         @"Penny",
                         @"Pennzoil",
                         @"Penske",
                         @"Peterbilt",
                         @"Peugeot",
                         @"Philbrick",
                         @"Phillip Morris",
                         @"Phillips",
                         @"Phillips 66",
                         @"Pierce Arrow",
                         @"Pierce-Arrow",
                         @"Pinzgauer",
                         @"Pioneer",
                         @"Pj",
                         @"Plant Jr.",
                         @"Plymouth",
                         @"Polarine",
                         @"Polaris",
                         @"Polly",
                         @"Pontiac",
                         @"Pontiac Jr",
                         @"Pope",
                         @"Porcelain",
                         @"Porsche",
                         @"Porsche Arova",
                         @"Powell",
                         @"Powerbike",
                         @"Precision",
                         @"Prevost",
                         @"Print Of 1969",
                         @"Pro Stock",
                         @"Pro Stock Wally",
                         @"Pro Weld Inc Iron",
                         @"Pro-1",
                         @"Profile",
                         @"Puch",
                         @"Puch-Sears",
                         @"Pugh",
                         @"Pulse",
                         @"Puma",
                         @"Pure Oil",
                         @"Puretest Oils",],
                @"Q" : @[@"Qlink",
                         @"Quaker State",
                         @"Quaker State Oil",
                         @"Qvale",],
                @"R" : @[@"Rabeneick",
                         @"Race Leathers  ",
                         @"Raleigh",
                         @"Rallye Yugoslavie",
                         @"Ralt",
                         @"Rambler",
                         @"Range Rover",
                         @"Rassey Rocket",
                         @"Rats",
                         @"Ravat",
                         @"Rayson Craft",
                         @"Razzia Talbot Logo",
                         @"Reading Standard",
                         @"Reconstructed",
                         @"Red Crown",
                         @"Redfish",
                         @"Redline 7000",
                         @"Redneck Rocket",
                         @"Regegade",
                         @"Reliant",
                         @"Remeq",
                         @"Renault",
                         @"Reo",
                         @"Replica",
                         @"Rex",
                         @"Rhino",
                         @"Richardson",
                         @"Richfield",
                         @"Richfield Gas Pump",
                         @"Rickman",
                         @"Rid",
                         @"Ridley",
                         @"Rienel",
                         @"Riva",
                         @"River Forest Haulin",
                         @"Rock Island",
                         @"Rockall",
                         @"Rolls Royce",
                         @"Rolls-Royce",
                         @"Rootes",
                         @"Rootes Sunbeam",
                         @"Roper",
                         @"Rotary",
                         @"Rotax Cheney",
                         @"Royal",
                         @"Royal Enfield",
                         @"RSC Collectibles",
                         @"Rudge",
                         @"Rudge-Whitworth",
                         @"Ruff And Tuff",
                         @"Rumely",
                         @"Rumely Oilpull",
                         @"Rumi",
                         @"Rupp Chaparral",],
                @"S" : @[@"S&W",
                         @"S-K Mechanics",
                         @"Saab",
                         @"Safari",
                         @"Safety Tested",
                         @"Saleen",
                         @"Salsbury",
                         @"Samson",
                         @"Sanger",
                         @"Sarolea",
                         @"Saturn",
                         @"Sbarro/BMW",
                         @"SC Collectibles",
                         @"Schwinn",
                         @"Schwinn Stingray",
                         @"Scorpion",
                         @"Scott",
                         @"Scripps",
                         @"SCSP",
                         @"Sea Lyon",
                         @"Seagrave",
                         @"Sears",
                         @"Seeley-Norton",
                         @"Shadow",
                         @"Shanghai",
                         @"Sharp",
                         @"Shay",
                         @"Sheffield Henderson",
                         @"Shelby",
                         @"Shelby American",
                         @"Shell",
                         @"Shell Marine",
                         @"Shepherd",
                         @"Sheppard",
                         @"Shoreline",
                         @"Siata",
                         @"Signal",
                         @"Signal Gas Pump",
                         @"Silver Eagle",
                         @"Silver King",
                         @"SIMCA",
                         @"Simplex",
                         @"Simpson Jumbo",
                         @"Sims",
                         @"Sinclair",
                         @"Sinclair Dino",
                         @"Sinclair Gas Station",
                         @"Sinclair Neon Sign",
                         @"Sinclair Opaline",
                         @"Skelly Neon Sign",
                         @"Skiff Craft",
                         @"Sky Chief",
                         @"Sky Princess",
                         @"Smart",
                         @"Smith",
                         @"Smp Baja",
                         @"Solar",
                         @"Soldier Field Stock",
                         @"Sonic",
                         @"Sparkbrook",
                         @"Sparta",
                         @"SPCN",
                         @"Spcns",
                         @"Spec",
                         @"Special",
                         @"Special Constn",
                         @"Special Construction",
                         @"Special Custom",
                         @"Speedster",
                         @"Spinal Tap",
                         @"Sportboat",
                         @"Sportster",
                         @"Sprint Car",
                         @"Squire",
                         @"Sstr",
                         @"St Martin",
                         @"Stacker",
                         @"Stan-Craft",
                         @"Standard",
                         @"Standard Oil Dealer",
                         @"Standard Red Crown",
                         @"Standard White Crown",
                         @"Star",
                         @"Starcraft",
                         @"Staudacher",
                         @"Steelcraft",
                         @"Steve McQueen",
                         @"Steyr-Daimler",
                         @"Steyr-Daimler Puch",
                         @"Stock",
                         @"Stock Engine",
                         @"Stone Boat Yard",
                         @"Storm",
                         @"Stratos",
                         @"Streblow",
                         @"Street Beast",
                         @"Street Rod",
                         @"Studebaker",
                         @"Stutz",
                         @"Subaru",
                         @"Sudlow",
                         @"Sun",
                         @"Sunbeam",
                         @"Sundoulos",
                         @"Sunflower",
                         @"Super Chevy",
                         @"Super Duty",
                         @"Super Stock National",
                         @"Superflow",
                         @"Superflow Tech",
                         @"Superformance",
                         @"Supervee",
                         @"Suzuki",
                         @"Swiss Made",],
                @"T" : @[@"Tandem Axel",
                         @"Taylor",
                         @"Taylor & Bates",
                         @"Team Penske",
                         @"Tear Drop Camping",
                         @"Television Model",
                         @"Terraplane",
                         @"Terrot",
                         @"Tesla",
                         @"Texaco",
                         @"Texaco Gas And Oil",
                         @"The Pit And The",
                         @"Thompson",
                         @"Thor",
                         @"Thunder Mountain",
                         @"Thunderbird",
                         @"Tiffin",
                         @"Tiger",
                         @"Tires And Batteries",
                         @"Titan",
                         @"TM",
                         @"Tn Trailer",
                         @"Tokheim 300",
                         @"Tokheim 325",
                         @"Top Stock",
                         @"Toro",
                         @"Total",
                         @"Toyota",
                         @"Trailer",
                         @"Transhaul",
                         @"Trevis Offy",
                         @"Trico",
                         @"Triton",
                         @"Triumph",
                         @"Triumph/BSA ",
                         @"Trivette",
                         @"Trojan",
                         @"Truscott",
                         @"TV Tommy Ivo",
                         @"TVR",
                         @"Twin City",
                         @"Twn Triumph",],
                @"U" : @[@"Ultima",
                         @"Ultra",
                         @"Ultra Stock",
                         @"United Bonus",
                         @"United Delco",
                         @"United Express",
                         @"Universal",
                         @"Us Royal",],
                @"V" : @[@"Valvoline",
                         @"Vectrix",
                         @"Veedol",
                         @"Velocette",
                         @"Velosolex",
                         @"Vengeance",
                         @"Ventnor",
                         @"Vertemati",
                         @"Vespa",
                         @"Victoria",
                         @"Vincent",
                         @"Vinchao Chinese",
                         @"Vintage",
                         @"Viper",
                         @"Voisin Biscuter",
                         @"Volkswagen",
                         @"Volvo",
                         @"Von Dutch",
                         @"Vukovich",],
                @"W" : @[@"Wagner",
                         @"Warlock",
                         @"Warrior",
                         @"Wash And Greasing",
                         @"Waterloo Boy",
                         @"Wayne 615",
                         @"Wayne Visible",
                         @"Wellcraft",
                         @"Wells Cargo",
                         @"Westcott",
                         @"Westcraft",
                         @"Wheego",
                         @"Whip",
                         @"Whippet",
                         @"Whistle",
                         @"White",
                         @"White Crown",
                         @"Whiticar",
                         @"Whizzer",
                         @"Whtie Flash",
                         @"Willis",
                         @"Willys",
                         @"Willys Overland",
                         @"Winnebago",
                         @"Winter Nationals",
                         @"Wise & Sons",
                         @"Wise Boat & Bus Works",
                         @"Wolfs Head",
                         @"Wolfs Head Motor Oil",
                         @"Wolfs Head Neon Sign",
                         @"Wood D Handle",
                         @"Woodstock",
                         @"Wurlitzer",],
                @"X" : @[@"X80 Mastercraft",],
                @"Y" : @[@"Yamaha",
                         @"Yamaha Castrol",
                         @"Yellow Jacket",],
                @"Z" : @[@"Zenith",
                         @"Zhe Jiang",
                         @"Zimmer",
                         @"ZL1 Engine",
                         @"Zundapp"],
                @"#" : @[@"1/4 Scale Replica",
                         @"25 Years Of Racing",
                         @"3d Custom",
                         @"435 Hp GM Winters",]};
    
    modelSectionTitles = [[models allKeys] sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
}

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
{
    // Return the number of sections.
    return [modelSectionTitles count];
}

//Title at each section
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section
{
    return [modelSectionTitles objectAtIndex:section];
}

//Number of rows
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    // Return the number of rows in the section.
    NSString *sectionTitle = [modelSectionTitles objectAtIndex:section];
    NSArray *sectionModels = [models objectForKey:sectionTitle];
    return [sectionModels count];
}

//Item at each cell
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"makeCell" forIndexPath:indexPath];
    
    // Configure the cell...
    NSString *sectionTitle = [modelSectionTitles objectAtIndex:indexPath.section];
    NSArray *sectionmodels = [models objectForKey:sectionTitle];
    NSString *model = [sectionmodels objectAtIndex:indexPath.row];
    cell.textLabel.text = model;
    
    return cell;
}

//Index on the left side
- (NSArray *)sectionIndexTitlesForTableView:(UITableView *)tableView
{
    return modelSectionTitles;
}

//If back button is pressed, pop current view from stack
- (IBAction)backButtonPressed:(id)sender {
    [self.navigationController popViewControllerAnimated:YES];
}



//Segue
-(void) prepareForSegue: (UIStoryboardSegue *)segue sender: (UITableViewCell *)sender {

    //Segue back to searchCar
    if ([segue.identifier isEqualToString:@"completedEntry"]) {
        modelLabel = sender.textLabel.text;
        self.modelName = modelLabel;
    }
}

@end
